# This workflow uses actions that are not certified by GitHub.

name: DBCHM

on:
  push:
    branches: [ master ]


jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: DBCHM_Sln.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
        
#     - uses: actions/cache@v1
#       id: cache
#       with:
#         path: ~/.nuget/packages
#         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        
    - name: NuGet Restore
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore $env:Solution_Name
  
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Rebuild the application
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
#     - name: Zip the release dir   
#     - uses: montudor/action-zip@v0.1.1
#       with:
#         args: zip -qq -r DBCHM.zip DBCHM\bin\Release        

    - run: dir /b

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: DBCHM
        path: |
          '~/DBChm/DBChm/bin/Release/**/*'
          !'~/DBChm/DBChm/**/*.pdb'
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

